#!/usr/bin/bash

read -p "Do you want to install vimrc? [Y/n]" vim_ans
# Vim config

if [[ $vim_ans != [nN] ]]
then
    source installers/vim
    echo ".vimrc installed"
else
    echo "Ok. Not installing vimrc"
fi

read -p "Do you want to add bashrc? [Y/n]" bash_ans

if [[ $bash_ans != [nN] ]]
then
    source installers/bash
    echo "bash config added"
else
    echo "Ok. Not adding bash config"
fi

read -p "Do you want to add i3 configs? [Y/n]" i3_ans

if [[ $i3_ans != [nN] ]]
then
    source installers/i3
    echo "i3 config added"
else
    echo "Ok. Not adding i3 config"
fi


